# Generated by Django 4.2 on 2023-05-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sever_1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
