# Generated by Django 4.2 on 2023-06-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sever_1", "0002_order_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="Фарба", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="maker",
            field=models.CharField(default="Farbman", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="surface",
            field=models.CharField(default="Бетон", max_length=50),
        ),
    ]
