# Generated by Django 4.2 on 2023-06-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sever_1", "0003_product_category_product_maker_product_surface"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinorder",
            name="capacity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productinorder",
            name="color",
            field=models.CharField(default="white", max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="new_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.IntegerField(default=0),
        ),
    ]
