# Generated by Django 4.2 on 2023-06-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sever_1", "0004_productinorder_capacity_productinorder_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default="fsoeuhfoszehfeoifzhes", max_length=1000),
        ),
    ]
