# Generated by Django 4.2 on 2023-06-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sever_1", "0006_alter_product_old_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.IntegerField(blank=True),
        ),
    ]
