# Generated by Django 4.2 on 2023-06-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sever_1", "0009_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.CharField(default="111111@gmail.com", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="post_office",
            field=models.CharField(default="7 відділення", max_length=50),
        ),
    ]
