# Generated by Django 4.2 on 2023-06-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sever_1", "0010_order_email_order_post_office"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinorder",
            name="capacity",
            field=models.CharField(max_length=20),
        ),
    ]
